### ISSUE TITLE
20 years of Cosmic Shear: Gravitational Lensing and Cosmology for the 2020’s

### ISSUE THREAD

**Issue by cheymans** [LSSTDESC/CosmologyMeetings#12]
@drphilmarshall

Not sure you're still in charge of this Phil, but if someone could add

Title: 20 years of Cosmic Shear: Gravitational Lensing and Cosmology for the 2020’s
Dates: 27th-31st July 2020
Location:  German Centre for Cosmological Lensing,  Ruhr Universitat Bochum.

that would be super - www still pending.

**Comment by rmandelb** [comment]
I only just discovered I wasn't watching this repo, so issues have piled up.  I just added it.  Thanks, Catherine!

**Comment by cheymans** [comment]
@rmandelb 
Many thanks Rachel - if there is a way of adding a weblink as well, that would be amazing.  Not to worry though if it is not possible.

https://cosmic-shear2020.rub.de/

**Comment by rmandelb** [comment]
Yes, that's easy enough - I put it in the "Notes" section, so the entry now looks like this -
<img width="451" alt="Screenshot 2020-01-09 08 13 39" src="https://user-images.githubusercontent.com/1454906/72070628-05267880-32b8-11ea-91bb-1446c570206e.png">

**Comment by cheymans** [comment]
Splendid - many thanks Rachel!
