### ISSUE TITLE
New Meeting: Workshop on Bayesian Deep Learning for Cosmology and Gravitational waves

### ISSUE THREAD

**Issue by BastienArcelin** [LSSTDESC/CosmologyMeetings#14]
@drphilmarshall

Hi Phil,

just to follow your post on Slack, the workshop on bayesian deep learning for cosmology and gravitational waves will be held on March 4-6 2020 at Laboratoire Astroparticules et Cosmologie, Université de Paris, France.

Best,

Bastien

**Comment by rmandelb** [comment]
Added!  Thanks.
