### ISSUE TITLE
Fall 2020 collaboration meetings?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/CosmologyMeetings#16]
I'm not seeing any DESC, DES or DESI collaboration meetings on the CosmologyMeetings after this month - is that because all planning is on hold because of COVID-19?

**Comment by rmandelb** [comment]
At least in DESC, we've decided to see how our first fully virtual collaboration meeting goes and get a better handle on the long-term prospects for virtual vs in-person meetings before further meetings go on the calendar.  Discussions are actively happening re: fall 2020 sprint week, and winter + summer 2021, just not at the stage of meetings on calendars.

I'm not sure about DES or DESI.
