### ISSUE TITLE
New Meeting: 25th International Conference on Particle Physics and Cosmology 2022 (COSMO 2022)

### ISSUE THREAD

**Issue by smurgia** [LSSTDESC/CosmologyMeetings#18]
@drphilmarshall
Dates: Monday, 22 August 2022 - Friday, 26 August 2022
URL: https://indico.cern.ch/event/886404/

**Comment by rmandelb** [comment]
Thanks!  I've added this.

**Comment by smurgia** [comment]
Thank you @rmandelb! This conference is now showing on the calendar! I have asked Phil to have admin privileges on behalf of the speakers bureau. Elisa says you can also do that. Let me know if that is possible.

**Comment by rmandelb** [comment]
So the Speakers Bureau is interested in maintaining this?  I'm glad to hear that's of interest.  If it's widely advertised within DESC I think it could be quite useful.  

Just to confirm, are you asking for (a) admin privileges to this repo or (b) admin privileges to the google calendar (or both).  For (b), I would need to know what email address you use for google calendars.

**Comment by smurgia** [comment]
Yes, when we discussed this a while ago within the SB, revamping Phil's calendar was what we agreed on. This is the easiest thing to do at this stage (I discussed this with Phil, months ago at this point, and he suggested we think about making this process sustainable and we can revisit that within the SB). 

Based on what I discussed with Phil and my current understanding (I might be wrong!), I would need both (a) and (b) privileges. My intention is to maintain the calendar for the time being on behalf of the SB. My understanding is that we can use the calendar to generate a list of events and periodically email the collaboration. 

My email address is smurgia@uci.edu

Thanks.

**Comment by rmandelb** [comment]
Oh great, I'm glad to hear you already discussed this with Phil.  (I would be a little uncomfortable changing privileges without somebody discussing with him, and had offered to Elisa that I could ask Phil about it when I see him in person next week - but this takes care of that problem.)

You should have just gotten notifications of your new administrative access to this repo and the calendar.  A few notes:

1. You are currently listed as the only repo admin, as you will see in the controls.  The reason for this is that both Phil and I are among the owners of the LSSTDESC GitHub org, so we had been able to do admin tasks in this repo without being added explicitly as admins.  If you wish to name other Speakers Bureau members as admins, you can certainly do so. But the repo is public, so if they just need to be able to see it and open issues, they should already be able to do so just fine.

2. Regarding the calendar, I gave you full access to not just add events but change with whom it is shared.  You will see that other people, primarily people who were involved in the DESC meetings committee in the past and in Phil's Management Team, also have access to add events or, in some cases, change sharing permissions (for example I have that access, and that's how I added you!).  You might want to think about giving the current Meetings Committee co-chairs (Andrew Hearin, Jonathan Blazek) access along with whoever you want on the Speakers Bureau.  It might be helpful if somebody from the current Management Team also has access... I see Katrin, Seth, and Pat have access for example, so keeping them in might make sense.

Please let me know if you have any questions about the above ^
