### ISSUE TITLE
New Meeting: UCLA Dark Matter 2025

### ISSUE THREAD

**Issue by pennalima** [LSSTDESC/CosmologyMeetings#22]
@drphilmarshall

Please, add this event. 

Name: UCLA Dark Matter 2025 
Date: Monday, 24 March 2025 - Thursday, 27 March 2025 
Local: University of California Los Angeles 
URL: https://darkmatter2025.pa.ucla.edu/

Thanks!
Mariana, for the DESC Speakers Bureau

**Comment by rmandelb** [comment]
Hi Mariana - in the calendar settings, it looks to me like you have access to edit the Cosmology Meetings calendar directly.

Can you please check/confirm?  I do not think you need Phil to add things for you.

**Comment by pennalima** [comment]
Hi Rachel, 
Thanks. 
In principle, I should have permission to edit the Cosmology Meetings calendar. 
But I did some tests (with no success). 

I will keep trying.

**Comment by pennalima** [comment]
Hi @rmandelb, 

I think I know the problem. The permission was given to my work account (pennalima@unb.br). 
Can you please give me access using pennalima@gmail.com?

**Comment by rmandelb** [comment]
Done!  Please let me know if it works.

**Comment by pennalima** [comment]
It works! 
Thank you so much!!!
