### ISSUE TITLE
New Meeting: Euclid Consortium Meeting, Helsinki, Finland, June 4-7 2019

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/CosmologyMeetings#8]
Meeting name: Euclid Consortium Meeting

Meeting location: Helsinki, Finland

Meeting dates: June 4-7, 2019

URL: http://www.physics.helsinki.fi/ec2019/

More Information:
More details to follow, to be sent to Euclideans and Friends of Euclid

**Comment by rmandelb** [comment]
This meeting was added to the calendar by @drphilmarshall .  Closing #8.
